name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
      env:
        ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}

    - name: Deploy to Fly.io
      uses: superfly/flyctl-actions@v1
      with:
        args: deploy  # Usa aquí los argumentos que necesites para el despliegue
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        ASTRO_STUDIO_APP_TOKEN: ${{ secrets.ASTRO_STUDIO_APP_TOKEN }}
